package com.ideax.judging.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INVALID_SCORE,
    RESULTS_NOT_READY,
    TEAM_HAS_JUDGING_RECORDS,
    JUDGE_HAS_JUDGING_RECORDS,
    RESET_UNAUTHORIZED,
    RESET_INVALID_PASSWORD,
    RESET_FAILED,
    INTERNAL_SERVER_ERROR
}
